### ISSUE TITLE
Support for monorepos

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [rrd108/vue-mess-detector-vscode#3]
It seems that not all vue files are found if you try to start it on a monorepo with some nesting.

**Comment by rrd108** [comment]
Yes, currently it search for the default folders.

What is your setup? It should be easy to add support for extra folders.

**Comment by sschneider-ihre-pvs** [comment]
<workspaceRoot>/apps/some-app/src/**/*.vue

**Comment by rrd108** [comment]
cc07883de52249301f3b04cf124d0a6d46011fde fixed
